### ISSUE TITLE
debian "demo" startup command.

### ISSUE THREAD

**Issue by genisd** [chyves/chyves.github.io#1]
The debian demo contains the following start command:

`chyves big-debbie start` in pane 2

For the first initial boot the iso should be specified (at least when I just tried. The video includes the iso as well). Should it say this perhaps?

`chyves big-debbie start debian-8.5.0-amd64-netinst.iso` in pane 2

I had hoped to make a PR to update that. But I think the text source is at asci cinema?

P.S.: Installing a debian guest was a breeze with the demo. Really impressed! :-)

**Comment by EpiJunkie** [comment]
Thank you for the compliment and bringing this to my attention.

My apologies for the delay. I remember reading this issue on a mobile and thinking the next day "I know there is a PR with 'debian' in the title, where is it."

I have since updated the comments for the video on [asciinema](https://asciinema.org).

I might rerecord the videos because now there is the global and guest property '`eject_iso_on_n_reboot`' which streamlines the interaction a little bit .
